server:
  port: 8080

spring:

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  sql:
    init:
      mode: always

jwt:
  access-secret-key: accessabcdefghijklmnopqrstuvwxyz
  access-token-valid-days: 99999

---

server:
  port: 8080

spring:

  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql:
    init:
      mode: always

jwt:
  access-secret-key: accessabcdefghijklmnopqrstuvwxyz
  access-token-valid-days: 99999

---

server:
  port: 8080

spring:

  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

  sql:
    init:
      mode: never

jwt:
  access-secret-key: accessabcdefghijklmnopqrstuvwxyz
  access-token-valid-days: 99999
