name: CD

on:
  push:
    branches: [ "develop", "main" ]

permissions: write-all

jobs:
  build:
    name: 빌드 및 OpenAPI 생성
    runs-on: ubuntu-latest

    steps:
      - name: 소스 코드 가져오기
        uses: actions/checkout@v4

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Gradle 패키지 캐싱
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Gradle 명령어 권한 부여
        run: chmod +x gradlew

      - name: OpenAPI 스펙 생성
        run: ./gradlew clean test --tests "*ControllerTest" -Dspring.profiles.active=dev

      - name: 애플리케이션 JAR 빌드
        run: ./gradlew bootJar

      - name: JAR 결과물 업로드
        uses: actions/upload-artifact@v4
        with:
          name: academy-jar
          path: build/libs/*.jar

      - name: OpenAPI 결과물 업로드
        uses: actions/upload-artifact@v4
        with:
          name: openapi-spec
          path: build/api-spec/openapi3.yaml

  publish-docker:
    name: Docker 이미지 배포
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 소스 코드 가져오기
        uses: actions/checkout@v4

      - name: JAR 결과물 다운로드
        uses: actions/download-artifact@v4
        with:
          name: academy-jar
          path: build/libs

      - name: Docker Buildx 설정
        uses: docker/setup-buildx-action@v3

      - name: Docker Hub 로그인
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker 이미지 빌드 및 푸시
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/academy-server:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/academy-server:${{ github.sha }}

  publish-api-docs:
    name: 📑 API 문서 배포
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: OpenAPI 결과물 다운로드
        uses: actions/download-artifact@v4
        with:
          name: openapi-spec
          path: .

      - name: API 문서 서버 레포 체크아웃
        uses: actions/checkout@v4
        with:
          repository: fprh13/academy-api-docs
          token: ${{ secrets.ACADEMY_API_DOCS_REPO_TOKEN }}
          path: api-docs-repo

      - name: API 문서 결과물 복사
        run: cp openapi3.yaml api-docs-repo/openapi3.yaml

      - name: API 문서 서버 레포에 반영
        run: |
          cd api-docs-repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add openapi3.yaml
          git commit -m "chore: API 문서 최신화" || echo "추가된 API 문서 작업이 없습니다."
          git push
